ci: implement a format checker workflow
Signed-off-by: Adria Montoto <75563346+adriamontoto@users.noreply.github.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -175,6 +175,51 @@ jobs:
           SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.head_sha }}
           SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
 
+  format:
+    name: Format Check Workflow - Python ${{ matrix.python-version }} on ${{ matrix.os }}
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 10
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest]
+        python-version: [3.13]
+
+    permissions:
+      contents: read
+
+    steps:
+      - name: 🛡️ Harden runner
+        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
+        with:
+          egress-policy: audit
+
+      - name: 📥 Checkout the repository
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          persist-credentials: false
+
+      - name: 🐍 Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: 📦 Install dependencies
+        run: make install-dev CI=true VERBOSE=true
+
+      - name: 🏃 Run Formatter
+        run: make format CI=true VERBOSE=true
+
+      - name: 🧐 Verify no changes
+        run: |
+          CHANGES=$(git status --porcelain)
+
+          if [[ -n "${CHANGES}" ]]; then
+            echo "::error file=.github/workflows/ci.yaml,title=Format Check Workflow Failed::Code is not formatted correctly. Please run 'make format' locally and commit the changes."
+
+            exit 1
+          fi
+
   lint:
     name: Lint Workflow - Python ${{ matrix.python-version }} on ${{ matrix.os }}
     runs-on: ${{ matrix.os }}
@@ -258,7 +303,7 @@ jobs:
 
   check-all:
     name: Check All Workflows Passed Workflow
-    needs: [test, lint, analyze]
+    needs: [test, format, lint, analyze]
     if: always()
     runs-on: ${{ matrix.os }}
     strategy:
@@ -304,14 +349,13 @@ jobs:
       - name: 📥 Checkout the repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
-          persist-credentials: false
           fetch-depth: 0
 
       - name: 🔖 Semantic Release
         id: released
         uses: python-semantic-release/python-semantic-release@0dc72ac9058a62054a45f6344c83a423d7f906a8 # v10.0.2
         with:
-          build: false
+          build: true
           push: true
           changelog: true
           commit: true
